version: "3"
networks:
        my_network:
                driver: bridge
services:
        server:
                build: .
                image: heaty566/hotel-server:latest
                networks:
                        - my_network
                ports:
                        - 1000:8080
